# Generated by Django 3.2.7 on 2021-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('views', models.PositiveIntegerField(verbose_name='Кол-во показов')),
                ('clicks', models.PositiveIntegerField(verbose_name='Кол-во кликов')),
                ('cost', models.FloatField(verbose_name='Стоимость кликов в рублях')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
